services:

  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.10.7
    container_name: sing-box
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./sing-box/:/etc/sing-box/
    command: -D /var/lib/sing-box -C /etc/sing-box/ run