services:
  commafeed:
    image: athou/commafeed:5.4.0-h2-jvm
    container_name: commafeed
    restart: unless-stopped
    volumes:
      - ./db:/commafeed/data
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commafeed.entrypoints=web,websecure"
      - "traefik.http.services.commafeed.loadbalancer.server.port=8082"
      - "traefik.http.routers.commafeed.rule=Host(`commafeed.pi.m1xxos.me`)"
      - "traefik.http.routers.commafeed.tls.certresolver=based"

networks:
  traefik_proxy:
    external: true