services:
  commafeed:
    image: athou/commafeed:5.4.0-h2-jvm
    container_name: commafeed
    restart: unless-stopped
    volumes:
      - ./db:/commafeed/data
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8082:8082
