services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.13.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - DOZZLE_REMOTE_AGENT=192.168.1.138:7007
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.entrypoints=websecure,web"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.pi.m1xxos.tech`)"
      - "traefik.http.routers.dozzle.service=dozzle"
      - "traefik.http.routers.dozzle.tls.certresolver=based"

networks:
  traefik_proxy:
    external: true